import type { Metadata } from 'next';
import { Header } from '@components/Header/Header';
import { Footer } from '@components/Footer/Footer';
import { Gtm } from '@components/misc/GTM';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Gtm />
      <body
        className={
          'font-newsreader selection:bg-secondary bg-white text-2xl text-black antialiased'
        }
      >
        {process.env.NODE_ENV === 'production' &&
          process.env.NEXT_PUBLIC_GTM && (
            <noscript>
              <iframe
                src={`https://www.googletagmanager.com/ns.html?id=${process.env.NEXT_PUBLIC_GTM}`}
                height="0"
                width="0"
                style={{ display: 'none', visibility: 'hidden' }}
              />
            </noscript>
          )}

        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
