import type { Metadata } from 'next';
import { Header } from '@components/Header/Header';
import { Footer } from '@components/Footer/Footer';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          'font-newsreader selection:bg-secondary bg-white text-2xl text-black antialiased'
        }
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
